export enum RoleEnum {
    ADMIN = 'ADMIN',
    USER = 'USER',
    EDITOR = 'EDITOR',
    HR_MANAGER = 'HR_MANAGER',
    FINANCE_MANAGER = 'FINANCE_MANAGER',
    INVENTORY_MANAGER = 'INVENTORY_MANAGER',
}